#ifndef __BVBS_ZSH_CONFIG__
#define __BVBS_ZSH_CONFIG__

#include <inttypes.h>
#include <stdbool.h>

void Cleanup();
void DoSetup();

#define MaxLocations 32
extern char* NAMES[];
extern char* LOCS[];
extern int8_t GROUPS[];
extern char* GitHubs[];
extern uint8_t numGitHubs;
extern uint8_t numLOCS;
extern bool CONFIG_DISABLE_LOCS_CHECKING;

extern char* GIT_EXCLUSIONS[];
extern uint8_t numGitExclusions;

extern bool CONFIG_GIT_AUTO_RESTORE_EXCLUSION;

extern bool CONFIG_LOWPROMPT_PATH_LIMIT;
extern int CONFIG_LOWPROMPT_PATH_MAXLEN;
extern bool CONFIG_LOWPROMPT_RETCODE;
extern bool CONFIG_LOWPROMPT_RETCODE_DECODE;
extern bool CONFIG_LOWPROMPT_TIMER;
extern char CONFIG_LOWPROMPT_START_CHAR[];
extern char CONFIG_LOWPROMPT_END_CHAR[];

extern bool CONFIG_PROMPT_OVERALL_ENABLE;

extern bool CONFIG_PROMPT_SSH;
extern bool CONFIG_PROMPT_TERMINAL_DEVICE;
extern bool CONFIG_PROMPT_TIME;
extern bool CONFIG_PROMPT_TIMEZONE;
extern bool CONFIG_PROMPT_DATE;
extern bool CONFIG_PROMPT_CALENDARWEEK;
extern bool CONFIG_PROMPT_PROXY;
extern bool CONFIG_PROMPT_NETWORK;
extern bool CONFIG_PROMPT_JOBS;
extern bool CONFIG_PROMPT_POWER;
extern bool CONFIG_PROMPT_GIT;
extern bool CONFIG_PROMPT_USER;
extern bool CONFIG_PROMPT_HOST;
extern char CONFIG_PROMPT_FILLER_CHAR[];

extern bool CONFIG_PROMPT_NET_IFACE;
extern bool CONFIG_PROMPT_NET_ADDITIONAL;
extern bool CONFIG_PROMPT_NET_ROUTE;
extern bool CONFIG_PROMPT_NET_LINKSPEED;

extern int CONFIG_GIT_MAXBRANCHES;
extern bool CONFIG_GIT_WARN_BRANCH_LIMIT;
extern bool CONFIG_GIT_REPOTYPE;
extern bool CONFIG_GIT_REPOTYPE_PARENT;
extern bool CONFIG_GIT_REPONAME;
extern bool CONFIG_GIT_BRANCHNAME;
extern bool CONFIG_GIT_BRANCH_OVERVIEW;
extern bool CONFIG_GIT_BRANCHSTATUS;
extern bool CONFIG_GIT_REMOTE;
extern bool CONFIG_GIT_COMMIT_OVERVIEW;
extern bool CONFIG_GIT_LOCALCHANGES;

extern int CONFIG_PROMPT_GIT_BRANCHLIMIT;
extern bool CONFIG_PROMPT_GIT_WARN_BRANCHLIMIT;
extern bool CONFIG_PROMPT_GIT_REPOTYPE;
extern bool CONFIG_PROMPT_GIT_REPOTYPE_PARENT;
extern bool CONFIG_PROMPT_GIT_REPONAME;
extern bool CONFIG_PROMPT_GIT_BRANCHNAME;
extern bool CONFIG_PROMPT_GIT_BRANCHINFO;
extern bool CONFIG_PROMPT_GIT_BRANCHSTATUS;
extern bool CONFIG_PROMPT_GIT_REMOTE;
extern bool CONFIG_PROMPT_GIT_COMMITS;
extern bool CONFIG_PROMPT_GIT_GITSTATUS;

extern bool CONFIG_LSGIT_WARN_BRANCHLIMIT;
extern int CONFIG_LSGIT_QUICK_BRANCHLIMIT;
extern bool CONFIG_LSGIT_QUICK_WARN_BRANCHLIMIT;
extern bool CONFIG_LSGIT_QUICK_REPOTYPE;
extern bool CONFIG_LSGIT_QUICK_REPOTYPE_PARENT;
extern bool CONFIG_LSGIT_QUICK_REPONAME;
extern bool CONFIG_LSGIT_QUICK_BRANCHNAME;
extern bool CONFIG_LSGIT_QUICK_BRANCHINFO;
extern bool CONFIG_LSGIT_QUICK_BRANCHSTATUS;
extern bool CONFIG_LSGIT_QUICK_REMOTE;
extern bool CONFIG_LSGIT_QUICK_COMMITS;
extern bool CONFIG_LSGIT_QUICK_GITSTATUS;
extern int CONFIG_LSGIT_THOROUGH_BRANCHLIMIT;
extern bool CONFIG_LSGIT_THOROUGH_WARN_BRANCHLIMIT;
extern bool CONFIG_LSGIT_THOROUGH_REPOTYPE;
extern bool CONFIG_LSGIT_THOROUGH_REPOTYPE_PARENT;
extern bool CONFIG_LSGIT_THOROUGH_REPONAME;
extern bool CONFIG_LSGIT_THOROUGH_BRANCHNAME;
extern bool CONFIG_LSGIT_THOROUGH_BRANCHINFO;
extern bool CONFIG_LSGIT_THOROUGH_BRANCHSTATUS;
extern bool CONFIG_LSGIT_THOROUGH_REMOTE;
extern bool CONFIG_LSGIT_THOROUGH_COMMITS;
extern bool CONFIG_LSGIT_THOROUGH_GITSTATUS;

extern bool DIPFALSCHEISSER_WARNINGS;
extern bool I_HAVE_ANCIENT_GIT;
#endif
